# Generated by Django 6.0.3 on 2026-05-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfiles',
            new_name='StudentProfile',
        ),
    ]
